<?php /**
 * @var \TieuMinh\SumUp1\Block\Post\View $block ;
 *
 */
if ($block->getPagerHtml()): ?>
    <div>
        <form method="get" action="<?= $block->getSearchUrl(); ?>">
            <input type="search" name="q" placeholder="<?= __('Search...') ?>"/>
            <button title="Submit" type="submit" style="margin: 20px;">Search
            </button>
        </form>
    </div>
    <div><?php echo $block->getPagerHtml(); ?></div>
<?php endif ?>

<?php $gridrecords = $block->getCustomCollection(); ?>
<?php if ($gridrecords && count($gridrecords)): ?>
    <div>
        <div class="content">
            <?php if (!empty($gridrecords->getData())): ?>
                <?php foreach ($gridrecords->getData() as $item): ?>
                    <div>
                        <a href="http://magento.gg/post/post/detail/id/<?=$item['post_id']?>"><h2><?= $item['title'] ?></h2></a>
                        <a href="http://magento.gg/post/post/detail/id/<?=$item['post_id']?>"><img src="<?= $item['thumbnail'] ?>" alt="image" height="300px" width="500px" href="<?php $block->getUrl('post/post/detail')?>id/<?=$item['post_id']?>"></a>
                        <p><?= $item['short_description'] ?>
                        <p><b>Category:<?= $gridrecords->cateName($item['post_id']) ?></b></p>
                        <p>
                            <?php if (!empty($gridrecords->tagName($item['post_id']))): ?>
                                <?php foreach ($gridrecords->tagName($item['post_id']) as $value): ?>
                                    <b><?= $value['name'] ?></b>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </p>
                        <a href="#"><u><i>Read more...</i></u></a></p>

                    </div>

                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </div>

    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('No any record.'); ?></span></div>
<?php endif ?>